// <auto-generated />
using LevelingCalculator.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LevelingCalculator.API.Migrations
{
    [DbContext(typeof(LevelingCalculatorDbContext))]
    [Migration("20240210102327_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LevelingCalculator.Repository.Model.CharRes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Elite")
                        .HasColumnType("int");

                    b.Property<int>("IDChar")
                        .HasColumnType("int");

                    b.Property<int>("IDRes1")
                        .HasColumnType("int");

                    b.Property<int>("IDRes2")
                        .HasColumnType("int");

                    b.Property<int>("IDRes3")
                        .HasColumnType("int");

                    b.Property<int>("LMD")
                        .HasColumnType("int");

                    b.Property<int>("ResN1")
                        .HasColumnType("int");

                    b.Property<int>("ResN2")
                        .HasColumnType("int");

                    b.Property<int>("ResN3")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDChar");

                    b.HasIndex("IDRes3");

                    b.ToTable("CharRes");
                });

            modelBuilder.Entity("LevelingCalculator.Repository.Model.Character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("LevelingCalculator.Repository.Model.Resource", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Craftable")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Own")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("LevelingCalculator.Repository.Model.TransactionalOutbox", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabella")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TransactionalOutboxes");
                });

            modelBuilder.Entity("LevelingCalculator.Repository.Model.CharRes", b =>
                {
                    b.HasOne("LevelingCalculator.Repository.Model.Character", "character")
                        .WithMany("char_ass")
                        .HasForeignKey("IDChar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelingCalculator.Repository.Model.Resource", "resource")
                        .WithMany("res_ass")
                        .HasForeignKey("IDRes3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("character");

                    b.Navigation("resource");
                });

            modelBuilder.Entity("LevelingCalculator.Repository.Model.Character", b =>
                {
                    b.Navigation("char_ass");
                });

            modelBuilder.Entity("LevelingCalculator.Repository.Model.Resource", b =>
                {
                    b.Navigation("res_ass");
                });
#pragma warning restore 612, 618
        }
    }
}
